spring:
  profiles:
    active : local
---
#server configuration
spring:
  profiles: production

server:
   port: 80
   address: 00.00.00.00
---
#local postgres configuration
spring:
  profiles: local

server:
  port: 8080
  address: localhost
---
# Database
db:
  driver: org.postgresql.Driver
  link: jdbc:postgresql://localhost:5432/brotherhood
  username: postgres
  password: postgres

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false
  format_sql: true
  use_sql_comments: true
  hbm2ddl.auto: false

entitymanager:
  packagesToScan: ua.com.hellomoto
